name: speech_recognition
description: A flutter plugin to use the speech recognition on iOS and Android
version: 1.0.0+1
environment:
   sdk: '<3.0.0'
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/speech_recognition

flutter:
  plugin:
    androidPackage: bz.rxla.flutter.speechrecognition
    pluginClass: SpeechRecognitionPlugin

dependencies:
  flutter:
    sdk: flutter
